@startuml
class CsvAmortizationScheduleWriter {
    + CsvAmortizationScheduleWriter(writer:TextWriter, calculator:IMonthlyPaymentCalculator)
    + WriteAmortizationSchedule(loan:ILoan) : void
}
@enduml
