@startuml LoanApp

hide empty members
skinparam linetype ortho

class Program {
    + {static} Main(args:string[]) : int
}
class MortgageParser {
    + Principal : decimal <<get>>
    + Term : int <<get>>
    + Rate : decimal <<get>>
    + Output : string? <<get>>
    + MortgageParser()
    + ParseArgs(args:string[]) : int
}
interface ILoan {
    + Principal : decimal <<get>>
    + Term : int <<get>>
    + Rate : decimal <<get>>
}
class Mortgage {
    + Principal : decimal <<get>>
    + Term : int <<get>>
    + Rate : decimal <<get>>
    + Mortgage(principal:decimal, term:int, rateStrategy:IInterestRateStrategy)
}
ILoan <|-- Mortgage
class CsvAmortizationScheduleWriter {
    + CsvAmortizationScheduleWriter(writer:TextWriter, calculator:IMonthlyPaymentCalculator)
    + WriteAmortizationSchedule(loan:ILoan) : void
}
class SpyInterestRate {
    + RateCalled : bool <<get>>
    + Rate : decimal <<get>>
}
IInterestRateStrategy <|-- SpyInterestRate
class DummyInterestRate {
    + Rate : decimal <<get>> = 0
}
IInterestRateStrategy <|-- DummyInterestRate
interface IInterestRateStrategy {
    + Rate : decimal <<get>>
}
class FixedInterestRate {
    + Rate : decimal <<get>>
}
IInterestRateStrategy <|-- FixedInterestRate
class FixedMonthlyPaymentCalculator {
    + CalculateMonthlyPayment(loan:ILoan) : decimal
}
IMonthlyPaymentCalculator <|-- FixedMonthlyPaymentCalculator
interface IMonthlyPaymentCalculator {
    + CalculateMonthlyPayment(loan:ILoan) : decimal
}

Program ..> Mortgage : <<uses>>
Program ..> MortgageParser : <<uses>>
Program ..> CsvAmortizationScheduleWriter : <<uses>>

Mortgage ..> IInterestRateStrategy : <<uses>>

CsvAmortizationScheduleWriter ..> IMonthlyPaymentCalculator : <<uses>>
CsvAmortizationScheduleWriter ..> ILoan : <<uses>>

FixedMonthlyPaymentCalculator ..> ILoan : <<uses>>

@enduml
